### ISSUE TITLE
Не работает в комбинации с RF24 библиотекой, для nRF24L01 модуля

### ISSUE THREAD

**Issue by neosonne** [GyverLibs/GyverBME280#1]
Попробовал уже две библиотеки и они либо не выдают ничего, либо не правильные значения. Но только я убираю инициализацию для NR24, то все начинает работать, есть идеи в чем может быть проблема? Тестирую на Wemos Mini, BME280 и nRF2401

**Comment by GyverLibs** [comment]
Что куда подключено?

Какой код от рф24 помимо инициализации есть в программе?

**Comment by neosonne** [comment]
о как быстро) я чуть позже отпишусь подробней, а то сейчас нужно уходить

**Comment by GyverLibs** [comment]
Уходи) мне просто уведомления на личную почту идут

**Comment by neosonne** [comment]
В общем так, убрал всё лишнее и оставил минимум кода. Попробовал по очереди отключать инициализацию RF24 и выяснилось что если убрать `radio.startListening();` то выдает нормальные значения. Значит скорей всего проблема в считывании данных параллельно пытаясь принять что-то по радио). Я не очень разбираюсь в SPI и I2C, но думаю возможная проблема в разных скоростях считывания. 

Сначала я пробовал библиотеку Adafruit_BME280 и там были неправильные значения, а в твоей библиотеки все значения нули. По отдельности всё работает, вместе нет.

nRF24L01 подключен так, только без конденсатора
![Wemos_nRF24L01_connection](https://user-images.githubusercontent.com/46954988/165504818-4ac504ae-5c43-4961-9f2c-8371eaa2a655.png)

BME280 

SDA -> D2
SCL -> D1

Код только инициализация и пример считывания данных с сенсора с твоего примера

```
#include <SPI.h>
#include <nRF24L01.h>
#include <RF24.h>

#include <GyverBME280.h>   

GyverBME280 bme; 

RF24 radio(D2, D8); // Pins for ESP Wemos Mini
const byte address[6] = "00001";

void setup() {
  Serial.begin(115200);
  
  bme.begin(); 

  radio.begin();
  radio.setPALevel(RF24_PA_LOW);
  radio.enableAckPayload();
  radio.enableDynamicPayloads();
  radio.openWritingPipe(address);
  radio.openReadingPipe(0, address);
  radio.startListening();

  delay(1000);
}

void loop() {
  MeasureBME280Data();
  delay(5000);
}

void MeasureBME280Data() {
  Serial.print("Temperature: ");
  Serial.print(bme.readTemperature());      
  Serial.println(" *C");

  Serial.print("Humidity: ");
  Serial.print(bme.readHumidity());          
  Serial.println(" %");

  float pressure = bme.readPressure();     
  Serial.print("Pressure: ");
  Serial.print(pressure / 100.0F);          
  Serial.print(" hPa , ");
  Serial.print(pressureToMmHg(pressure));   
  Serial.println(" mm Hg");
  Serial.print("Altitide: ");
  Serial.print(pressureToAltitude(pressure));
  Serial.println("");
}
```

Есть какие идеи, что можно попробовать? Вчера ковырялся в коде библиотек, но что-бы разобраться нужно больше времени чем у меня сейчас на это есть.

**Comment by GyverLibs** [comment]
А с чего это вообще должно работать, если пин D2 используется и туда и туда?))) Нет ну вот серьезно?

**Comment by neosonne** [comment]
Так в этом дело?) Ну как я и написал, я в этом не очень шарю, помню что были какие-то пины общие для такта, вот и не задумываясь подключил

**Comment by GyverLibs** [comment]
Какие то да, общие. Но в пределах одного интерфейса, а тут один модуль на SPI, второй на I2C

**Comment by neosonne** [comment]
Ок, спасибо за быстрый ответ. Буду дальше разбираться, потом еще отпишусь и закрою ветку, может кому пригодиться :)

**Comment by neosonne** [comment]
Итак решение проблемы: нужно изменить дефолтные пины для I2C и пересоединить туда BME280. Сделать это можно добавив в `setup() ` следующую строчку ` Wire.begin(D1, D3); //SDA, SCL` и соответственно подсоединить BME280 на D1 и D3.
Всем спасибо за внимание :)

**Comment by GyverLibs** [comment]
Зачем? Можно ведь просто перенести этот пин рф24 на любой другой.

**Comment by neosonne** [comment]
ну да так тоже можно) просто я начал поиск с другой стороны и это было первое попавшееся решение. В любом случае, я не знал что это решено на уровне софта и пины можно переконфигурировать. Это может помочь в будущем при разводе платы
