### ISSUE TITLE
Не работает на ESP8266

### ISSUE THREAD

**Issue by karas1k8** [GyverLibs/GyverBME280#2]
Датчик выдаёт вместо температуры и влажности нули.
Версия библиотеки: 1.5
МК: NodeMCU (ESP8266)
Версия: Arduino IDE 1.8.16
Простой код, выводящий температуру в serial
P.S. Баг также проявляется с DS18B20
P.P.S Датчик нормально работает с таким же кодом на arduino nano

`#include <GyverBME280.h>

GyverBME280 bme;

void setup() {
  bme.begin();
  Serial.begin(9600);
}

void loop() {
  Serial.println(bme.readTemperature(););
  delay(1000);
}`

**Comment by GyverLibs** [comment]
- Библиотека протестирована на esp8266/32, работает великолепно. 99% датчик подключен в неправильные пины (аппаратный I2C), или пины неправильно указаны (программный I2C), см. документацию на NodeMCU
- Для DS18B20 нужна другая библиотека по понятным причинам
